title: Quentin ANDRÉ
logo: "/images/logo.jpg"
description: >
  <br><br>
  Diplômé du Master Informatique parcours IMAGINA (Images, Games and INtelligent Agents) de l'université de Montpellier
  <br><br>
  <a href="https://www.linkedin.com/in/quentin-andré-9791b0111/">LinkedIn</a>

theme: jekyll-theme-minimal
